### ISSUE TITLE
UTDATE error

### ISSUE THREAD

**Issue by kfkaplan** [igrins/plp#12]
When I try to run the 2.1-alpha.1 version of the PLP, the PLP does not appear to be correctly reading in the date when trying to run the "thar" or "sky-wvlsol" recipes.  It appears to work fine for the "flat" but as an example  I get the following error when trying to run "thar" on the date 20141023:

grad11kk:plp-2.1-alpha.1 kfkaplan$ python ./igr_pipe.py thar 20141023
[31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
/Volumes/IGRINS_Data/plp-2.1-alpha.1/recipes/libs/igrins_config.py:36: UserWarning: no recipe.config is found. Internal default will be used.
  warnings.warn("no recipe.config is found. Internal default will be used.")
loading calib/primary/20140525/FLAT_.centroid_solutions.json
Traceback (most recent call last):
  File "./igr_pipe.py", line 54, in <module>
    argh.dispatch(parser)
  File "./external/argh/argh/dispatching.py", line 125, in dispatch
    for line in lines:
  File "./external/argh/argh/dispatching.py", line 202, in _execute_command
    for line in result:
  File "./external/argh/argh/dispatching.py", line 185, in _call
    result = args.function(_positional, *_keywords)
  File "/Volumes/IGRINS_Data/plp-2.1-alpha.1/recipes/recipe_thar.py", line 30, in thar
    starting_obsids, config_file)
  File "/Volumes/IGRINS_Data/plp-2.1-alpha.1/recipes/libs/recipe_base.py", line 40, in __call__
    self.process(utdate, bands, starting_obsids, config_file)
  File "/Volumes/IGRINS_Data/plp-2.1-alpha.1/recipes/libs/recipe_base.py", line 59, in process
    self.run_selected_bands_with_recipe(utdate, selected, bands)
  File "/Volumes/IGRINS_Data/plp-2.1-alpha.1/recipes/libs/recipe_base.py", line 36, in run_selected_bands_with_recipe
    self.run_selected_bands(utdate, selected2, bands)
  File "/Volumes/IGRINS_Data/plp-2.1-alpha.1/recipes/recipe_thar.py", line 24, in run_selected_bands
    self.config)
  File "/Volumes/IGRINS_Data/plp-2.1-alpha.1/recipes/recipe_thar.py", line 361, in process_thar_band
    thar_products = get_thar_products(helper, band, obsids)
  File "/Volumes/IGRINS_Data/plp-2.1-alpha.1/recipes/recipe_thar.py", line 108, in get_thar_products
    ap = get_simple_aperture(helper, band, thar_master_obsid)
  File "/Volumes/IGRINS_Data/plp-2.1-alpha.1/recipes/recipe_thar.py", line 93, in get_simple_aperture
    bottomup_solutions = get_bottom_up_solution(helper, band, thar_master_obsid)
  File "/Volumes/IGRINS_Data/plp-2.1-alpha.1/recipes/recipe_thar.py", line 78, in get_bottom_up_solution
    mastername=flaton_basename)
  File "/Volumes/IGRINS_Data/plp-2.1-alpha.1/recipes/libs/products.py", line 152, in load
    v = self.load_one(fn)
  File "/Volumes/IGRINS_Data/plp-2.1-alpha.1/recipes/libs/products.py", line 239, in load_one
    return json.load(open(fn))
IOError: [Errno 2] No such file or directory: 'calib/primary/20140525/FLAT_.centroid_solutions.json'
grad11kk:plp-2.1-alpha.1 kfkaplan$

**Comment by leejjoon** [comment]
Kyle,

There has some changes which I will address in a more formal release note. Meanwhile,

* Please try the "register-sky" recipe instead of "thar". There is no need to change the recipe_log file (but you need to have a "SKY" entry in it). So, the order is : flat -> register-sky -> wvlsol-sky -> a0v-* > stellar|extended-*

* If the problem persist, check the recipe_log file and  only leave one entry of "flat" (comment out the others). You may need to wipe out the "calib/primary/$UTDATE" directory and start from the beginning.

If these does not help, let me know.

-JJ

**Comment by leejjoon** [comment]
For the "thar" recipe, a fix is on the way and will be included in the next alpha release.

**Comment by kfkaplan** [comment]
That made it work.  Thank you.
