### ISSUE TITLE
[register-sky] Error: No JSON object could be decoded

### ISSUE THREAD

**Issue by navarete** [igrins/plp#21]
Hi,

I'm trying to process some of my data using the PLP v2 and when I execute the 'register-sky' pipeline I got the message: "No JSON object could be decoded". Do you have any idea what could be causing this error?

```
$ python ./igr_pipe.py register-sky 20210427
loading /home/navarete/plp-master/calib/primary/20210427/FLAT_SDCH_20210427_0001.hotpix_mask.fits
loading /home/navarete/plp-master/calib/primary/20210427/FLAT_SDCH_20210427_0011.deadpix_mask.fits
loading /home/navarete/plp-master/calib/primary/20210427/FLAT_SDCH_20210427_0011.bias_mask.fits
saving /home/navarete/plp-master/outdata/20210427/SDCH_20210427_0035.stacked.fits
WARNING: AstropyDeprecationWarning: "clobber" was deprecated in version 2.0 and will be removed in a future version. Use argument "overwrite" instead. [astropy.utils.decorators]
WARNING:astropy:AstropyDeprecationWarning: "clobber" was deprecated in version 2.0 and will be removed in a future version. Use argument "overwrite" instead.
loading /home/navarete/plp-master/outdata/20210427/SDCH_20210427_0035.stacked.fits
loading /home/navarete/plp-master/calib/primary/20210427/FLAT_SDCH_20210427_0011.centroid_solutions.json
/home/navarete/anaconda3/envs/igr-pipe/lib/python2.7/site-packages/numpy/lib/nanfunctions.py:1076: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
saving /home/navarete/plp-master/calib/primary/20210427/SDCH_20210427_0035.oned_spec.json
Traceback (most recent call last):
  File "./igr_pipe.py", line 64, in <module>
    argh.dispatch(parser, argv=argv)
  File "/home/navarete/plp-master/igrins/external/argh/dispatching.py", line 125, in dispatch
    for line in lines:
  File "/home/navarete/plp-master/igrins/external/argh/dispatching.py", line 202, in _execute_command
    for line in result:
  File "/home/navarete/plp-master/igrins/external/argh/dispatching.py", line 185, in _call
    result = args.function(*positional, **keywords)
  File "/home/navarete/plp-master/igrins/libs/recipe_factory.py", line 43, in _recipe_func
    **kwargs)
  File "/home/navarete/plp-master/igrins/libs/recipe_base.py", line 115, in process
    **kwargs)
  File "/home/navarete/plp-master/igrins/libs/recipe_factory.py", line 22, in run_selected_bands_with_recipe
    self.config, **kwargs)
  File "/home/navarete/plp-master/igrins/recipes/process_wvlsol_v0.py", line 548, in process_band
    identify_orders(obsset)
  File "/home/navarete/plp-master/igrins/recipes/process_wvlsol_v0.py", line 231, in identify_orders
    ref_spec_path, ref_spectra = obsset.fetch_ref_data(kind=ref_spec_key)
  File "/home/navarete/plp-master/igrins/libs/obs_set.py", line 139, in fetch_ref_data
    return self.caldb.fetch_ref_data(self.band, kind)
  File "/home/navarete/plp-master/igrins/libs/cal_db.py", line 326, in fetch_ref_data
    kind=kind)
  File "/home/navarete/plp-master/igrins/libs/master_calib.py", line 111, in fetch_ref_data
    return fn, loader(fn)
  File "/home/navarete/plp-master/igrins/libs/master_calib.py", line 83, in json_loader
    return json.load(open(fn))
  File "/home/navarete/anaconda3/envs/igr-pipe/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/home/navarete/anaconda3/envs/igr-pipe/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/home/navarete/anaconda3/envs/igr-pipe/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/navarete/anaconda3/envs/igr-pipe/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by kfkaplan** [comment]
@navarete I realize it's been a few years, but were you ever able to solve this issue?  It sounds like you need to create a sky frame in your recipe_log file for the night.  If you are having trouble, let us know.

**Comment by kfkaplan** [comment]
I am going to close the issue for now.  @navarete if you are still working in this, feel free send me a copy of your recipe log file and I can probably help you fix this if it is still a problem.
